questions = [
    "How does Sahar Finance help individuals and businesses with their financial security?",
    "What is the primary goal of Sahar Finance's financial services?",
    "What are the key services Sahar Finance provides?",
    "How does Sahar Finance's Wealth Management service help its clients?",
    "What types of insurance solutions are offered by Sahar Finance?",
    "What is included in Sahar Finance's Life Insurance offering?",
    "How does Critical Illness insurance provided by Sahar Finance protect its clients?",
    "What benefits does Disability Insurance offer, and who is it ideal for?",
    "What does the Health & Dental Insurance package from Sahar Finance include?",
    "What does the Group Benefits package entail, and which businesses can benefit from it?",
    "How does Sahar Finance’s Mortgage Protection service work?",
    "What does the Travel Insurance plan cover?",
    "What are the key features of Sahar Finance’s Cash Flow Management service?",
    "How does Sahar Finance optimize tax strategies for its clients?",
    "What is involved in Sahar Finance’s Retirement Planning service?",
    "How does Sahar Finance assist with Business Planning for business owners?",
    "What is included in Sahar Finance’s Education Planning service for families?",
    "How does Sahar Finance help clients with Estate Planning?",
    "What are the coverage options available for life insurance with Sahar Finance?",
    "What types of life insurance policies are available, and what are their features?",
    "Who would benefit most from Sahar Finance’s Life Insurance offerings?",
    "What is the pricing for Life Insurance and what coverage options are available?",
    "How much does Sahar Finance’s Critical Illness coverage cost, and what does it cover?",
    "What are the pricing options for Disability Insurance from Sahar Finance?",
    "What are the pricing plans for Health & Dental Insurance, and what is covered?",
    "How much does Sahar Finance’s Group Benefits plan cost, and what does it include?",
    "What are the pricing options for Mortgage Protection Insurance, and how does it work?",
    "How much does Travel Insurance cost through Sahar Finance, and what does it cover?",
    "What is the process to get started with Sahar Finance services?",
    "How does Sahar Finance tailor its financial plans to meet client goals?",
    "What is included in the initial consultation with Sahar Finance?",
    "What happens during the strategy development stage with Sahar Finance?",
    "How does Sahar Finance implement the financial strategies for its clients?",
    "What is the customer satisfaction rating for Sahar Finance’s services?",
    "How does Sahar Finance ensure customer satisfaction with its financial products?",
    "What are the consultation timings for Sahar Finance?",
    "How can a potential client schedule a consultation with Sahar Finance?",
    "What contact information is provided for getting in touch with Sahar Finance?",
    "How can clients stay connected with Sahar Finance through social media?"
]
