questions = [
    "How does Oxa Finance help individuals and businesses with their financial security?",
    "What is the primary goal of Oxa Finance's financial services?",
    "What are the key services Oxa Finance provides?",
    "How does Oxa Finance's Wealth Management service help its clients?",
    "What types of insurance solutions are offered by Oxa Finance?",
    "What is included in Oxa Finance's Life Insurance offering?",
    "How does Critical Illness insurance provided by Oxa Finance protect its clients?",
    "What benefits does Disability Insurance offer, and who is it ideal for?",
    "What does the Health & Dental Insurance package from Oxa Finance include?",
    "What does the Group Benefits package entail, and which businesses can benefit from it?",
    "How does Oxa Finance’s Mortgage Protection service work?",
    "What does the Travel Insurance plan cover?",
    "What are the key features of Oxa Finance’s Cash Flow Management service?",
    "How does Oxa Finance optimize tax strategies for its clients?",
    "What is involved in Oxa Finance’s Retirement Planning service?",
    "How does Oxa Finance assist with Business Planning for business owners?",
    "What is included in Oxa Finance’s Education Planning service for families?",
    "How does Oxa Finance help clients with Estate Planning?",
    "What are the coverage options available for life insurance with Oxa Finance?",
    "What types of life insurance policies are available, and what are their features?",
    "Who would benefit most from Oxa Finance’s Life Insurance offerings?",
    "What is the pricing for Life Insurance and what coverage options are available?",
    "How much does Oxa Finance’s Critical Illness coverage cost, and what does it cover?",
    "What are the pricing options for Disability Insurance from Oxa Finance?",
    "What are the pricing plans for Health & Dental Insurance, and what is covered?",
    "How much does Oxa Finance’s Group Benefits plan cost, and what does it include?",
    "What are the pricing options for Mortgage Protection Insurance, and how does it work?",
    "How much does Travel Insurance cost through Oxa Finance, and what does it cover?",
    "What is the process to get started with Oxa Finance services?",
    "How does Oxa Finance tailor its financial plans to meet client goals?",
    "What is included in the initial consultation with Oxa Finance?",
    "What happens during the strategy development stage with Oxa Finance?",
    "How does Oxa Finance implement the financial strategies for its clients?",
    "What is the customer satisfaction rating for Oxa Finance’s services?",
    "How does Oxa Finance ensure customer satisfaction with its financial products?",
    "What are the consultation timings for Oxa Finance?",
    "How can a potential client schedule a consultation with Oxa Finance?",
    "What contact information is provided for getting in touch with Oxa Finance?",
    "How can clients stay connected with Oxa Finance through social media?"
]
